import json
import base64
import os
import tempfile
import unittest
from pathlib import Path
from types import SimpleNamespace
from unittest.mock import patch

from open3d_artist.agent_bridge import agent_catalog, agent_pool_status, run_agent_build, run_agent_plan, run_production_agent
from open3d_artist.contracts import digest_json
from open3d_artist.geometry import generate_glb
from open3d_artist.project import Project, ProjectError
from open3d_artist.reference import validate_reference_spec


class FakeRunner:
    def __init__(self, output="{}\n", returncode=0):
        self.output, self.returncode, self.calls = output, returncode, []

    def __call__(self, argv, **kwargs):
        self.calls.append(argv)
        if argv[-1] == "--version":
            return SimpleNamespace(returncode=0, stdout=b"fake 1\n", stderr=b"")
        return SimpleNamespace(returncode=self.returncode, stdout=self.output.encode(), stderr=b"fake error")


def completed_run(root):
    receipt = {"schema_version": "0.2.0", "status": "PASS", "brief_id": "fixture"}
    (root / "run_receipt.json").write_text(json.dumps(receipt), encoding="utf-8")
    return receipt


def reference_spec(asset_id):
    components = [
        {"id": "body", "role": "primary form", "level": "macro", "visible_features": ["silhouette"]},
        {"id": "trim", "role": "secondary form", "level": "meso", "visible_features": ["edge bands"]},
        {"id": "hardware", "role": "functional detail", "level": "micro", "visible_features": ["fastener"]},
    ]
    return {
        "schema_version": "0.1.0", "profile": "img2threejs", "target_asset_id": asset_id,
        "suitability": "pass", "subject": "a stylized prop", "silhouette": {"primary": "compact rounded body"},
        "components": components,
        "detail_inventory": [{"id": f"detail-{index}", "component": components[index % 3]["id"], "feature": f"feature {index}", "implementation": "separate beveled geometry", "evidence": "visible"} for index in range(5)],
        "materials": [{"id": "paint", "region": "body", "finish": "matte", "evidence": "visible"}, {"id": "metal", "region": "hardware", "finish": "brushed", "evidence": "inferred"}],
        "build_passes": ["blockout", "structural-pass", "form-refinement", "material-pass", "surface-pass", "lighting-pass", "interaction-pass", "optimization-pass"],
        "unseen_regions": ["back side is not visible"],
        "review_policy": {"on_failure": "refine-code", "require_side_by_side": True, "max_corrections": 2},
    }


class ProductionAgentReceiptTests(unittest.TestCase):
    def test_agent_build_runs_blender_worker_and_adopts_passing_glb(self):
        source = {
            "schema_version": "0.1.0", "asset_id": "AGENT-SOURCE-001", "kind": "prop", "units": "m",
            "dimensions": {"width": 2, "depth": 2, "height": 2}, "parts": [{"part_id": "body", "role": "body"}],
            "geometry": {"triangle_budget": {"max": 1000}, "primitives": [{"part_id": "body", "type": "box", "size": {"x": 1, "y": 1, "z": 1}}]},
        }
        generated = {**source, "asset_id": "AGENT-GENERATED-001", "dimensions": {"width": 0.5, "depth": 0.5, "height": 0.5}}

        class FakeWorker:
            def run_agent_build(self, script, contract, output, *, timeout):
                output.mkdir(parents=True, exist_ok=True)
                (output / "asset.glb").write_bytes(generate_glb(generated))
                (output / "scene.blend").write_bytes(b"blend")
                return {"sandbox": "fake", "process": {"status": "PASS", "returncode": 0, "duration_ms": 1, "output": ""}}

        def fake_agent(argv, **kwargs):
            workspace = Path(kwargs["cwd"])
            references = json.loads((workspace / "referenced_assets.json").read_text(encoding="utf-8"))
            request = json.loads((workspace / "request.json").read_text(encoding="utf-8"))
            self.assertEqual([item["asset_id"] for item in references], ["AGENT-SOURCE-001"])
            self.assertEqual(request["referenced_asset_ids"], ["AGENT-SOURCE-001"])
            (workspace / "asset.json").write_text(json.dumps(generated), encoding="utf-8")
            (workspace / "build.py").write_text("# generated by fake agent", encoding="utf-8")
            return SimpleNamespace(returncode=0, stdout=b"files ready", stderr=b"")

        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory) / "project"
            root.mkdir()
            (root / "asset.yaml").write_text(json.dumps(source), encoding="utf-8")
            project = Project.init(root, root / "asset.yaml")
            result = run_agent_build("codex", "build the requested prop", root, runner=fake_agent, which=lambda _: "/bin/fake", worker=FakeWorker(), referenced_asset_ids=["AGENT-SOURCE-001"], create_asset=True)
            self.assertEqual(result["status"], "PASS")
            self.assertFalse(result["project_state_unchanged"])
            self.assertIn("dimensions_autofit", result["mutation"])
            self.assertEqual(project.current()["geometry_source"], "blender")
            self.assertEqual(project.load_current_asset()["asset_id"], generated["asset_id"])
            self.assertEqual(project.validate()["status"], "PASS")

    def test_agent_build_stages_a_valid_reference_image_without_echoing_data(self):
        source = {
            "schema_version": "0.1.0", "asset_id": "AGENT-SOURCE-001", "kind": "prop", "units": "m",
            "dimensions": {"width": 2, "depth": 2, "height": 2}, "parts": [{"part_id": "body", "role": "body"}],
            "geometry": {"triangle_budget": {"max": 1000}, "primitives": [{"part_id": "body", "type": "box", "size": {"x": 1, "y": 1, "z": 1}}]},
        }
        generated = {**source, "asset_id": "AGENT-GENERATED-001"}
        png = b"\x89PNG\r\n\x1a\nreference"

        class FakeWorker:
            def run_agent_build(self, script, contract, output, *, timeout):
                output.mkdir(parents=True, exist_ok=True)
                (output / "asset.glb").write_bytes(generate_glb(generated))
                (output / "scene.blend").write_bytes(b"blend")
                return {"sandbox": "fake", "process": {"status": "PASS", "returncode": 0, "duration_ms": 1, "output": ""}}

        def fake_agent(argv, **kwargs):
            workspace = Path(kwargs["cwd"])
            self.assertEqual((workspace / "reference-image.png").read_bytes(), png)
            (workspace / "asset.json").write_text(json.dumps(generated), encoding="utf-8")
            (workspace / "build.py").write_text("# generated by fake agent", encoding="utf-8")
            (workspace / "reference_spec.json").write_text(json.dumps(reference_spec(generated["asset_id"])), encoding="utf-8")
            return SimpleNamespace(returncode=0, stdout=b"files ready", stderr=b"")

        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory); (root / "asset.yaml").write_text(json.dumps(source), encoding="utf-8")
            project = Project.init(root, root / "asset.yaml")
            result = run_agent_build("codex", "build from the reference", root, runner=fake_agent, which=lambda _: "/bin/fake", worker=FakeWorker(), reference_image={"name": "house.png", "mime_type": "image/png", "data": "data:image/png;base64," + base64.b64encode(png).decode()}, reference_pipeline="img2threejs")
            self.assertEqual(result["status"], "PASS")
            self.assertNotIn("data", result["reference_image"])
            self.assertEqual(result["reference_spec"]["summary"]["details"], 5)
            self.assertEqual(project.current()["agent_build"]["reference_spec_digest"], result["reference_spec"]["digest"])

    def test_img2threejs_reference_spec_is_checked_before_blender(self):
        source = {
            "schema_version": "0.1.0", "asset_id": "AGENT-SOURCE-001", "kind": "prop", "units": "m",
            "dimensions": {"width": 2, "depth": 2, "height": 2}, "parts": [{"part_id": "body", "role": "body"}],
            "geometry": {"triangle_budget": {"max": 1000}, "primitives": [{"part_id": "body", "type": "box", "size": {"x": 1, "y": 1, "z": 1}}]},
        }
        called = []

        class FakeWorker:
            def run_agent_build(self, script, contract, output, *, timeout):
                called.append(True)
                return {"process": {"status": "PASS"}}

        def fake_agent(argv, **kwargs):
            workspace = Path(kwargs["cwd"])
            (workspace / "asset.json").write_text(json.dumps({**source, "asset_id": "AGENT-GENERATED-001"}), encoding="utf-8")
            (workspace / "build.py").write_text("# generated by fake agent", encoding="utf-8")
            return SimpleNamespace(returncode=0, stdout=b"files ready", stderr=b"")

        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory); (root / "asset.yaml").write_text(json.dumps(source), encoding="utf-8")
            Project.init(root, root / "asset.yaml")
            result = run_agent_build("codex", "build from the reference", root, runner=fake_agent, which=lambda _: "/bin/fake", worker=FakeWorker(), reference_pipeline="img2threejs", reference_image={"name": "house.png", "mime_type": "image/png", "data": "data:image/png;base64," + base64.b64encode(b"\x89PNG\r\n\x1a\nreference").decode()}, create_asset=True)
            self.assertEqual(result["reason"], "REFERENCE_SPEC_MISSING")
            self.assertEqual(called, [])

    def test_reference_spec_validator_rejects_shallow_inventory(self):
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "reference_spec.json"
            value = reference_spec("AGENT-GENERATED-001")
            value["detail_inventory"] = value["detail_inventory"][:2]
            path.write_text(json.dumps(value), encoding="utf-8")
            with self.assertRaises(ValueError):
                validate_reference_spec(path, target_asset_id="AGENT-GENERATED-001")

    def test_agent_build_rejects_output_for_the_selected_edit_target(self):
        source = {
            "schema_version": "0.1.0", "asset_id": "AGENT-SOURCE-001", "kind": "prop", "units": "m",
            "dimensions": {"width": 2, "depth": 2, "height": 2}, "parts": [{"part_id": "body", "role": "body"}],
            "geometry": {"triangle_budget": {"max": 1000}, "primitives": [{"part_id": "body", "type": "box", "size": {"x": 1, "y": 1, "z": 1}}]},
        }
        generated = {**source, "asset_id": "AGENT-WRONG-001"}

        class FakeWorker:
            def run_agent_build(self, script, contract, output, *, timeout):
                self.called = True
                return {"sandbox": "fake", "process": {"status": "PASS", "returncode": 0, "duration_ms": 1, "output": ""}}

        def fake_agent(argv, **kwargs):
            workspace = Path(kwargs["cwd"])
            (workspace / "asset.json").write_text(json.dumps(generated), encoding="utf-8")
            (workspace / "build.py").write_text("# wrong target", encoding="utf-8")
            return SimpleNamespace(returncode=0, stdout=b"files ready", stderr=b"")

        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory); (root / "asset.yaml").write_text(json.dumps(source), encoding="utf-8")
            project = Project.init(root, root / "asset.yaml")
            result = run_agent_build("codex", "edit the selected prop", root, runner=fake_agent, which=lambda _: "/bin/fake", target_asset_id=source["asset_id"], worker=FakeWorker())
            self.assertEqual(result["reason"], "TARGET_ASSET_MISMATCH")
            self.assertTrue(result["project_state_unchanged"])
            self.assertEqual(project.current()["asset_id"], source["asset_id"])

    def test_plan_bridge_is_read_only_and_bounded_to_fixed_agent_cli(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory); (root / ".open3d").mkdir()
            fake = FakeRunner("read-only plan")
            result = run_agent_plan("codex", "inspect semantic parts", root, runner=fake, which=lambda _: "/bin/fake")
            self.assertEqual(result["status"], "PASS")
            self.assertTrue(result["project_state_unchanged"])
            self.assertEqual(fake.calls[0][1:4], ["exec", "--sandbox", "read-only"])

    def test_opencode_model_override_is_passed_without_pool(self):
        with tempfile.TemporaryDirectory() as directory, patch.dict(os.environ, {"OPEN3D_OPENCODE_MODEL": "nvidia/minimaxai/minimax-m3"}, clear=False):
            root = Path(directory); (root / ".open3d").mkdir()
            fake = FakeRunner("read-only plan")
            result = run_agent_plan("opencode", "inspect semantic parts", root, runner=fake, which=lambda _: "/bin/fake")
            self.assertEqual(result["status"], "PASS")
            self.assertIn("nvidia/minimaxai/minimax-m3", fake.calls[0])

    def test_fixed_read_only_bridge_writes_digest_linked_receipt(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory); receipt = completed_run(root)
            digest = digest_json(receipt)
            fake = FakeRunner(json.dumps({"agent_receipt": {"production_receipt_digest": digest}}))
            result = run_production_agent("codex", root, runner=fake, which=lambda _: "/bin/fake")
            self.assertEqual(result["status"], "PASS")
            self.assertEqual(result["production_receipt_digest"], digest)
            self.assertEqual(fake.calls[1][1:4], ["exec", "--sandbox", "read-only"])
            self.assertTrue((root / "agent_process_receipt.json").is_file())

    def test_rejects_unsafe_inputs_and_agent_digest_mismatch(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory); completed_run(root)
            with self.assertRaises(ProjectError): run_production_agent("shell", root)
            with self.assertRaises(ProjectError): run_production_agent("codex", root, output_root=root / "other")
            fake = FakeRunner(json.dumps({"agent_receipt": {"production_receipt_digest": "sha256:bad"}}))
            result = run_production_agent("codex", root, runner=fake, which=lambda _: "/bin/fake")
            self.assertEqual(result["reason"], "RECEIPT_DIGEST_MISMATCH")

    def test_missing_and_failed_cli_are_truthful_and_output_is_bounded(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory); completed_run(root)
            missing = run_production_agent("claude", root, which=lambda _: None)
            self.assertEqual(missing["status"], "UNAVAILABLE")
            fake = FakeRunner("x" * 100000, returncode=1)
            failed = run_production_agent("codex", root, runner=fake, which=lambda _: "/bin/fake")
            self.assertEqual(failed["status"], "FAILED")
            self.assertLessEqual(len(failed["stdout"]), 16 * 1024 + len("...[truncated]"))

    def test_catalog_exposes_only_authenticated_external_agents(self):
        def runner(argv, **kwargs):
            if argv[-1] == "--version":
                return SimpleNamespace(returncode=0, stdout=(argv[0] + " 1\n").encode(), stderr=b"")
            if argv[1:3] == ["login", "status"]:
                return SimpleNamespace(returncode=0, stdout=b"Logged in using ChatGPT\n", stderr=b"")
            if argv[1:4] == ["auth", "status", "--json"]:
                return SimpleNamespace(returncode=0, stdout=b'{"loggedIn":true}\n', stderr=b"")
            return SimpleNamespace(returncode=0, stdout=b"Credentials\n2 credentials\n", stderr=b"")

        with patch.dict(os.environ, {}, clear=True):
            agents = agent_catalog(runner=runner, which=lambda agent: f"/bin/{agent}")
        self.assertEqual([agent["agent_id"] for agent in agents], ["codex", "claude", "opencode"])
        self.assertTrue(all(agent["status"] == "ACTIVE" and agent["execution"] == "READY" for agent in agents))

    def test_shared_pool_is_authenticated_without_echoing_token(self):
        class Response:
            status = 200

            def __enter__(self):
                return self

            def __exit__(self, *_):
                return False

        def opener(request, timeout=0):
            self.assertEqual(request.full_url, "https://router.example/v1/models")
            self.assertTrue(request.get_header("Authorization").endswith("secret"))
            return Response()

        with patch.dict(os.environ, {"OPEN3D_AGENT_POOL_URL": "https://router.example", "OPEN3D_AGENT_POOL_TOKEN": "secret"}, clear=False):
            result = agent_pool_status(opener=opener)
        self.assertEqual(result["status"], "ACTIVE")
        self.assertNotIn("secret", json.dumps(result))


if __name__ == "__main__":
    unittest.main()
