import json
import tempfile
import unittest
from pathlib import Path
from types import SimpleNamespace

from open3d_artist.agent_bridge import run_agent_build, run_agent_plan, run_production_agent
from open3d_artist.contracts import digest_json
from open3d_artist.geometry import generate_glb
from open3d_artist.project import Project, ProjectError


class FakeRunner:
    def __init__(self, output="{}\n", returncode=0):
        self.output, self.returncode, self.calls = output, returncode, []

    def __call__(self, argv, **kwargs):
        self.calls.append(argv)
        if argv[-1] == "--version":
            return SimpleNamespace(returncode=0, stdout=b"fake 1\n", stderr=b"")
        return SimpleNamespace(returncode=self.returncode, stdout=self.output.encode(), stderr=b"fake error")


def completed_run(root):
    receipt = {"schema_version": "0.2.0", "status": "PASS", "brief_id": "fixture"}
    (root / "run_receipt.json").write_text(json.dumps(receipt), encoding="utf-8")
    return receipt


class ProductionAgentReceiptTests(unittest.TestCase):
    def test_agent_build_runs_blender_worker_and_adopts_passing_glb(self):
        source = {
            "schema_version": "0.1.0", "asset_id": "AGENT-SOURCE-001", "kind": "prop", "units": "m",
            "dimensions": {"width": 2, "depth": 2, "height": 2}, "parts": [{"part_id": "body", "role": "body"}],
            "geometry": {"triangle_budget": {"max": 1000}, "primitives": [{"part_id": "body", "type": "box", "size": {"x": 1, "y": 1, "z": 1}}]},
        }
        generated = {**source, "asset_id": "AGENT-GENERATED-001", "dimensions": {"width": 0.5, "depth": 0.5, "height": 0.5}}

        class FakeWorker:
            def run_agent_build(self, script, contract, output, *, timeout):
                output.mkdir(parents=True, exist_ok=True)
                (output / "asset.glb").write_bytes(generate_glb(generated))
                (output / "scene.blend").write_bytes(b"blend")
                return {"sandbox": "fake", "process": {"status": "PASS", "returncode": 0, "duration_ms": 1, "output": ""}}

        def fake_agent(argv, **kwargs):
            workspace = Path(kwargs["cwd"])
            (workspace / "asset.json").write_text(json.dumps(generated), encoding="utf-8")
            (workspace / "build.py").write_text("# generated by fake agent", encoding="utf-8")
            return SimpleNamespace(returncode=0, stdout=b"files ready", stderr=b"")

        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory) / "project"
            root.mkdir()
            (root / "asset.yaml").write_text(json.dumps(source), encoding="utf-8")
            project = Project.init(root, root / "asset.yaml")
            result = run_agent_build("codex", "build the requested prop", root, runner=fake_agent, which=lambda _: "/bin/fake", worker=FakeWorker())
            self.assertEqual(result["status"], "PASS")
            self.assertFalse(result["project_state_unchanged"])
            self.assertIn("dimensions_autofit", result["mutation"])
            self.assertEqual(project.current()["geometry_source"], "blender")
            self.assertEqual(project.load_current_asset()["asset_id"], generated["asset_id"])
            self.assertEqual(project.validate()["status"], "PASS")

    def test_plan_bridge_is_read_only_and_bounded_to_fixed_agent_cli(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory); (root / ".open3d").mkdir()
            fake = FakeRunner("read-only plan")
            result = run_agent_plan("codex", "inspect semantic parts", root, runner=fake, which=lambda _: "/bin/fake")
            self.assertEqual(result["status"], "PASS")
            self.assertTrue(result["project_state_unchanged"])
            self.assertEqual(fake.calls[0][1:4], ["exec", "--sandbox", "read-only"])

    def test_fixed_read_only_bridge_writes_digest_linked_receipt(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory); receipt = completed_run(root)
            digest = digest_json(receipt)
            fake = FakeRunner(json.dumps({"agent_receipt": {"production_receipt_digest": digest}}))
            result = run_production_agent("codex", root, runner=fake, which=lambda _: "/bin/fake")
            self.assertEqual(result["status"], "PASS")
            self.assertEqual(result["production_receipt_digest"], digest)
            self.assertEqual(fake.calls[1][1:4], ["exec", "--sandbox", "read-only"])
            self.assertTrue((root / "agent_process_receipt.json").is_file())

    def test_rejects_unsafe_inputs_and_agent_digest_mismatch(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory); completed_run(root)
            with self.assertRaises(ProjectError): run_production_agent("shell", root)
            with self.assertRaises(ProjectError): run_production_agent("codex", root, output_root=root / "other")
            fake = FakeRunner(json.dumps({"agent_receipt": {"production_receipt_digest": "sha256:bad"}}))
            result = run_production_agent("codex", root, runner=fake, which=lambda _: "/bin/fake")
            self.assertEqual(result["reason"], "RECEIPT_DIGEST_MISMATCH")

    def test_missing_and_failed_cli_are_truthful_and_output_is_bounded(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory); completed_run(root)
            missing = run_production_agent("claude", root, which=lambda _: None)
            self.assertEqual(missing["status"], "UNAVAILABLE")
            fake = FakeRunner("x" * 100000, returncode=1)
            failed = run_production_agent("codex", root, runner=fake, which=lambda _: "/bin/fake")
            self.assertEqual(failed["status"], "FAILED")
            self.assertLessEqual(len(failed["stdout"]), 16 * 1024 + len("...[truncated]"))


if __name__ == "__main__":
    unittest.main()
